### ISSUE TITLE
java.io.FileNotFoundException: http://www.w3.org/TR/REC-xsl/DTD/xsl.dtd

### ISSUE THREAD

**Issue by jmartinsCx** [sorcerdon/FOP.NetCore#2]
I have a problem with the project I'm working that I get this exception "javax.xml.transform.TransformerException: 'java.io.FileNotFoundException: http://www.w3.org/TR/REC-xsl/DTD/xsl.dtd'" in the "transformer.transform(src, res)" line even with the same code that you suggested.

**Comment by sorcerdon** [comment]
@jmartinsCx  I see you closed the issue. What was the core issue and your resolution?

**Comment by jmartinsCx** [comment]
> @jmartinsCx I see you closed the issue. What was the core issue and your resolution?

I was trying to access in my xslt file a resource that did not exist and this was giving me the error.
